name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - 'data/**'
      - '.github/workflows/data.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        institution: ['uq', 'qut', 'griffith']
    steps:
      - uses: actions/checkout@master
      - name: Upload
        run: |
          aws s3 cp ./data/${{ matrix.institution }} s3://unifinal-${{ matrix.institution }}/data --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-2'
